import type { User, Task, Role, TaskType, Priority, Project, Notification, KanbanColumnData } from './types';

export const USERS: User[] = [
  { id: '1', username: 'admin', email: 'admin@taskflow.com', password: 'Admin@123', role: 'Admin', status: 'active', designation: 'Project Lead', phoneNumber: '+1 (555) 123-4567', bio: 'I am the administrator for the AgileBridge platform.' },
  { id: '2', username: 'Project Manager', email: 'pm@taskflow.com', password: 'pmpassword', role: 'Manager', status: 'active' },
  { id: '3', username: 'Dev User', email: 'dev@taskflow.com', password: 'userpassword', role: 'Backend', status: 'active' },
  { id: '4', username: 'Another User', email: 'user@taskflow.com', password: 'userpassword', role: 'Frontend', status: 'active' },
  { id: '5', username: 'Design User', email: 'design@taskflow.com', password: 'userpassword', role: 'Designer', status: 'active' },
];

export const KANBAN_COLUMNS: KanbanColumnData[] = [
    { id: 'to-do', title: 'To Do', color: 'border-blue-500' },
    { id: 'in-progress', title: 'In Progress', color: 'border-yellow-500' },
    { id: 'in-review', title: 'In Review', color: 'border-purple-500' },
    { id: 'done', title: 'Done', color: 'border-green-500' },
];

export const TASKS: Task[] = [
    {
        id: 'TASK-1',
        projectId: 'PROJ-1',
        title: 'Design login and signup pages',
        description: 'Create high-fidelity mockups for the user authentication flow, including login, signup, and forgot password pages.',
        status: 'done',
        assignedRole: 'Designer',
        estimatedHours: 8,
        timeSpent: 8,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'High',
        type: 'Task',
        deadline: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-2',
        projectId: 'PROJ-1',
        title: 'Develop user authentication API endpoints',
        description: 'Build the necessary API endpoints for user registration, login, and session management.',
        status: 'done',
        assignedRole: 'Backend',
        estimatedHours: 12,
        timeSpent: 12,
        createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'High',
        type: 'Task',
        deadline: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-3',
        projectId: 'PROJ-1',
        title: 'Implement frontend for authentication',
        description: 'Connect the frontend forms for login, signup, and password reset to the backend APIs.',
        status: 'in-review',
        assignedRole: 'Frontend',
        estimatedHours: 10,
        timeSpent: 9,
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Medium',
        type: 'Task',
        deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-4',
        projectId: 'PROJ-1',
        title: 'Design the main Kanban board UI',
        description: 'Create wireframes and final designs for the main task board, including columns and task cards.',
        status: 'in-progress',
        assignedRole: 'Designer',
        estimatedHours: 6,
        timeSpent: 2,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Medium',
        type: 'Task',
        deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-5',
        projectId: 'PROJ-1',
        title: 'Set up database schema for tasks and users',
        description: 'Define and implement the database schema for storing user and task information, including roles and relationships.',
        status: 'in-progress',
        assignedRole: 'Backend',
        estimatedHours: 8,
        timeSpent: 1,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'High',
        type: 'Task',
        deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // Overdue
    },
    {
        id: 'TASK-6',
        projectId: 'PROJ-1',
        title: 'Build the Kanban board drag-and-drop functionality',
        description: 'Implement the client-side logic for dragging and dropping tasks between columns on the Kanban board.',
        status: 'to-do',
        assignedRole: 'Frontend',
        estimatedHours: 16,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'High',
        type: 'Bug',
        deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-7',
        projectId: 'PROJ-1',
        title: 'Develop API for task state management',
        description: 'Create backend endpoints to handle creating, updating, and deleting tasks, and changing their status.',
        status: 'to-do',
        assignedRole: 'Backend',
        estimatedHours: 10,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Medium',
        type: 'Task',
    },
     {
        id: 'TASK-8',
        projectId: 'PROJ-1',
        title: 'Create Admin panel for user role management',
        description: 'Build a UI for administrators to view all users and assign or change their roles.',
        status: 'to-do',
        assignedRole: 'Manager',
        estimatedHours: 8,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Low',
        type: 'Task',
        deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-9',
        projectId: 'PROJ-2',
        title: 'Plan mobile app architecture',
        description: 'Outline the overall architecture for the native mobile apps, including technology stack and component breakdown.',
        status: 'to-do',
        assignedRole: 'Manager',
        estimatedHours: 20,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'High',
        type: 'Task',
    },
    {
        id: 'TASK-10',
        projectId: 'PROJ-2',
        title: 'Design mobile splash screen',
        description: 'Create the initial splash screen and loading indicators for the mobile app.',
        status: 'to-do',
        assignedRole: 'Designer',
        estimatedHours: 4,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Medium',
        type: 'Task',
    },
];

export const PROJECTS: Project[] = [
    {
        id: 'PROJ-1',
        name: 'AgileBridge Platform',
        key: 'ABP',
        description: 'Development of the main AgileBridge project management platform.',
        color: 'hsl(var(--primary))',
        status: 'active',
        completion: 45,
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        issues: 8,
        members: [{id: '1'}, {id: '2'}, {id: '3'}, {id: '4'}, {id: '5'}],
    },
    {
        id: 'PROJ-2',
        name: 'Mobile App Initiative',
        key: 'MAI',
        description: 'A new initiative to create a native mobile application for iOS and Android.',
        color: 'hsl(var(--chart-2))',
        status: 'active',
        completion: 10,
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        issues: 3,
        members: [{id: '2'}, {id: '3'}, {id: '4'}],
    },
    {
        id: 'PROJ-3',
        name: 'Website Redesign',
        key: 'WR',
        description: 'A complete overhaul of the public-facing marketing website.',
        color: 'hsl(var(--chart-5))',
        status: 'active',
        completion: 75,
        createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        issues: 2,
        members: [{id: '5'}, {id: '3'}],
    }
];

export const NOTIFICATIONS: Notification[] = [
    {
        id: '1',
        title: 'Project Update',
        message: 'Task "Design login page" moved to In Progress.',
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        read: false,
    },
    {
        id: '2',
        title: 'Project Update',
        message: 'Task "Develop user auth API" moved to In Review.',
        createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        read: false,
    },
    {
        id: '3',
        title: 'Project Update',
        message: 'New task "Implement frontend auth" assigned to a user.',
        createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        read: false,
    },
    {
        id: '4',
        title: 'Project Update',
        message: 'Task "Design Kanban board" due soon.',
        createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
        read: true,
    },
    {
        id: '5',
        title: 'Project Update',
        message: 'Task "Setup database schema" is overdue.',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        read: true,
    },
];


export const ROLES: Role[] = ['Frontend', 'Backend', 'Designer', 'Manager', 'Admin'];

export const TASK_TYPES: TaskType[] = ['Bug', 'Task'];
export const PRIORITIES: Priority[] = ['Low', 'Medium', 'High'];
