import type { User, Task, Role } from './types';

export const USERS: User[] = [
  { id: '1', username: 'Admin User', email: 'admin@taskflow.com', role: 'Admin', avatar: 'https://i.pravatar.cc/150?u=admin' },
  { id: '2', username: 'Project Manager', email: 'pm@taskflow.com', role: 'Project Manager', avatar: 'https://i.pravatar.cc/150?u=pm' },
  { id: '3', username: 'Frontend Dev', email: 'frontend@taskflow.com', role: 'Frontend', avatar: 'https://i.pravatar.cc/150?u=frontend' },
  { id: '4', username: 'Backend Dev', email: 'backend@taskflow.com', role: 'Backend', avatar: 'https://i.pravatar.cc/150?u=backend' },
  { id: '5', username: 'UI/UX Designer', email: 'designer@taskflow.com', role: 'Designer', avatar: 'https://i.pravatar.cc/150?u=designer' },
];

export const TASKS: Task[] = [
    {
        id: 'TASK-1',
        title: 'Design login and signup pages',
        description: 'Create high-fidelity mockups for the user authentication flow, including login, signup, and forgot password pages.',
        status: 'Done',
        assignedRole: 'Designer',
        estimatedHours: 8,
        timeSpent: 8,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-2',
        title: 'Develop user authentication API endpoints',
        description: 'Build the necessary API endpoints for user registration, login, and session management.',
        status: 'Done',
        assignedRole: 'Backend',
        estimatedHours: 12,
        timeSpent: 12,
        createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-3',
        title: 'Implement frontend for authentication',
        description: 'Connect the frontend forms for login, signup, and password reset to the backend APIs.',
        status: 'In Progress',
        assignedRole: 'Frontend',
        estimatedHours: 10,
        timeSpent: 4,
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-4',
        title: 'Design the main Kanban board UI',
        description: 'Create wireframes and final designs for the main task board, including columns and task cards.',
        status: 'In Progress',
        assignedRole: 'Designer',
        estimatedHours: 6,
        timeSpent: 2,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-5',
        title: 'Set up database schema for tasks and users',
        description: 'Define and implement the database schema for storing user and task information, including roles and relationships.',
        status: 'To Do',
        assignedRole: 'Backend',
        estimatedHours: 8,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-6',
        title: 'Build the Kanban board drag-and-drop functionality',
        description: 'Implement the client-side logic for dragging and dropping tasks between columns on the Kanban board.',
        status: 'To Do',
        assignedRole: 'Frontend',
        estimatedHours: 16,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'TASK-7',
        title: 'Develop API for task state management',
        description: 'Create backend endpoints to handle creating, updating, and deleting tasks, and changing their status.',
        status: 'To Do',
        assignedRole: 'Backend',
        estimatedHours: 10,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
     {
        id: 'TASK-8',
        title: 'Create Admin panel for user role management',
        description: 'Build a UI for administrators to view all users and assign or change their roles.',
        status: 'To Do',
        assignedRole: 'Project Manager',
        estimatedHours: 8,
        timeSpent: 0,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

export const ROLES: Role[] = ['Frontend', 'Backend', 'Designer', 'Project Manager', 'Admin'];
